In [1]:
%matplotlib inline

import pandas as pd
import numpy as np
import warnings
import pylab as plt
import seaborn as sns
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
import kaggle

In [2]:
salaries=pd.read_csv('data/model_data/salaries_USD.csv')

In [3]:
test=pd.read_csv('data/model_data/test_USD.csv')

In [4]:
salaries_num= salaries._get_numeric_data()

In [5]:
salaries_num.columns

Index(['Unnamed: 0', 'work_year', 'salary', 'salary_in_usd', 'remote_ratio'], dtype='object')

In [6]:
salaries_num.drop('Unnamed: 0', axis=1, inplace=True)

In [7]:
test_num = test._get_numeric_data()

In [8]:
test_num.drop('Unnamed: 0', axis=1, inplace=True)

In [9]:
salaries_num.head()

work_year  salary  salary_in_usd  remote_ratio
0       2022  140250         140250           100
1       2022  135000         135000           100
2       2021  100000         100000           100
3       2021  270000         270000           100
4       2022  153000         153000            50

# x es salaries

In [10]:
from sklearn.model_selection import train_test_split as tts  # el alias es cosa mia

X=salaries_num.drop(['salary', 'salary_in_usd'], axis=1)  # separacion X y

y=salaries_num.salary_in_usd

In [11]:
X_train, X_test, y_train, y_test = tts(X, y, train_size=0.8, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((222, 2), (56, 2), (222,), (56,))

**Regresión Lineal**

In [12]:
from sklearn.linear_model import LinearRegression as LinReg
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.linear_model import ElasticNet



# se inician los modelos
linreg=LinReg()
lasso=Lasso()
ridge=Ridge()
elastic=ElasticNet()

**SVR**

In [13]:
from sklearn.svm import SVR  # support vector regressor

svr=SVR()

**Random Forest**

In [19]:
from sklearn.ensemble import RandomForestRegressor as RFR  
from sklearn.tree import ExtraTreeRegressor as ETR

rfr=RFR()
etr=ETR()

In [20]:
from sklearn.ensemble import GradientBoostingRegressor as GBR

from xgboost import XGBRegressor as XGBR

from catboost import CatBoostRegressor as CTR

from lightgbm import LGBMRegressor as LGBMR


gbr=GBR()
xgbr=XGBR()
ctr=CTR()
lgbmr=LGBMR()

In [21]:
linreg.fit(X_train, y_train)
lasso.fit(X_train, y_train)
ridge.fit(X_train, y_train)
elastic.fit(X_train, y_train)

ElasticNet()

In [22]:
linreg.coef_

array([2589.30892024,   62.44916357])

In [23]:
svr.fit(X_train, y_train)

SVR()

In [24]:
rfr.fit(X_train, y_train)
etr.fit(X_train, y_train)

ExtraTreeRegressor()

In [25]:
gbr.fit(X_train, y_train)

GradientBoostingRegressor()

In [26]:
xgbr.fit(X_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, ...)

In [27]:
ctr.fit(X_train, y_train, verbose=0)

In [28]:
lgbmr.fit(X_train, y_train)

LGBMRegressor()

In [52]:
linreg.predict(X_test)

array([139117.9705751 , 141707.27949534, 139117.9705751 , 141707.27949534,
       139117.9705751 , 135995.51239635, 136528.66165486, 141707.27949534,
       141707.27949534, 135462.36313785, 133406.20347611, 135462.36313785,
       139117.9705751 , 139117.9705751 , 141707.27949534, 135995.51239635,
       135462.36313785, 141707.27949534, 141707.27949534, 135462.36313785,
       141707.27949534, 135995.51239635, 141707.27949534, 132873.05421761,
       141707.27949534, 135462.36313785, 135462.36313785, 141707.27949534,
       141707.27949534, 139117.9705751 , 139117.9705751 , 133406.20347611,
       141707.27949534, 139117.9705751 , 141707.27949534, 141707.27949534,
       135462.36313785, 141707.27949534, 141707.27949534, 141707.27949534,
       135995.51239635, 132873.05421761, 133406.20347611, 135462.36313785,
       136528.66165486, 135462.36313785, 141707.27949534, 141707.27949534,
       132873.05421761, 141707.27949534, 139117.9705751 , 135462.36313785,
       136528.66165486, 1

In [55]:
df = pd.DataFrame(linreg.predict(X_test), 
             columns=['salary_in_usd'])

In [56]:
df

salary_in_usd
0   139117.970575
1   141707.279495
2   139117.970575
3   141707.279495
4   139117.970575
5   135995.512396
6   136528.661655
7   141707.279495
8   141707.279495
9   135462.363138
10  133406.203476
11  135462.363138
12  139117.970575
13  139117.970575
14  141707.279495
15  135995.512396
16  135462.363138
17  141707.279495
18  141707.279495
19  135462.363138
20  141707.279495
21  135995.512396
22  141707.279495
23  132873.054218
24  141707.279495
25  135462.363138
26  135462.363138
27  141707.279495
28  141707.279495
29  139117.970575
30  139117.970575
31  133406.203476
32  141707.279495
33  139117.970575
34  141707.279495
35  141707.279495
36  135462.363138
37  141707.279495
38  141707.279495
39  141707.279495
40  135995.512396
41  132873.054218
42  133406.203476
43  135462.363138
44  136528.661655
45  135462.363138
46  141707.279495
47  141707.279495
48  132873.054218
49  141707.279495
50  139117.970575
51  135462.363138
52  136528.661655
53  135995.512396
54  141707.279495
55  135995.512396

In [53]:
lasso.predict(X_test)

array([139118.95127863, 141706.06132749, 139118.95127863, 141706.06132749,
       139118.95127863, 135996.51502871, 136531.84122976, 141706.06132749,
       141706.06132749, 135461.18882766, 133409.40497984, 135461.18882766,
       139118.95127863, 139118.95127863, 141706.06132749, 135996.51502871,
       135461.18882766, 141706.06132749, 141706.06132749, 135461.18882766,
       141706.06132749, 135996.51502871, 141706.06132749, 132874.07877879,
       141706.06132749, 135461.18882766, 135461.18882766, 141706.06132749,
       141706.06132749, 139118.95127863, 139118.95127863, 133409.40497984,
       141706.06132749, 139118.95127863, 141706.06132749, 141706.06132749,
       135461.18882766, 141706.06132749, 141706.06132749, 141706.06132749,
       135996.51502871, 132874.07877879, 133409.40497984, 135461.18882766,
       136531.84122976, 135461.18882766, 141706.06132749, 141706.06132749,
       132874.07877879, 141706.06132749, 139118.95127863, 135461.18882766,
       136531.84122976, 1

In [58]:
df1 = pd.DataFrame(linreg.predict(X_test), 
             columns=['salary_in_usd'])

In [59]:
df1

salary_in_usd
0   139117.970575
1   141707.279495
2   139117.970575
3   141707.279495
4   139117.970575
5   135995.512396
6   136528.661655
7   141707.279495
8   141707.279495
9   135462.363138
10  133406.203476
11  135462.363138
12  139117.970575
13  139117.970575
14  141707.279495
15  135995.512396
16  135462.363138
17  141707.279495
18  141707.279495
19  135462.363138
20  141707.279495
21  135995.512396
22  141707.279495
23  132873.054218
24  141707.279495
25  135462.363138
26  135462.363138
27  141707.279495
28  141707.279495
29  139117.970575
30  139117.970575
31  133406.203476
32  141707.279495
33  139117.970575
34  141707.279495
35  141707.279495
36  135462.363138
37  141707.279495
38  141707.279495
39  141707.279495
40  135995.512396
41  132873.054218
42  133406.203476
43  135462.363138
44  136528.661655
45  135462.363138
46  141707.279495
47  141707.279495
48  132873.054218
49  141707.279495
50  139117.970575
51  135462.363138
52  136528.661655
53  135995.512396
54  141707.279495
55  135995.512396

In [61]:
pd.read_csv('data/old_data/sample.csv')

id  salary_in_usd
0      0          23351
1      1          48576
2      2          86706
3      3          13457
4      4          23096
..   ...            ...
102  102          98408
103  103          11305
104  104          70769
105  105          53423
106  106          72091

[107 rows x 2 columns]

In [31]:
ridge.predict(X_test)[:10]

array([139129.4539809 , 141693.36573846, 139129.4539809 , 141693.36573846,
       139129.4539809 , 136006.89883427, 136565.54222334, 141693.36573846,
       141693.36573846, 135448.2554452 ])

In [32]:
elastic.predict(X_test)[:10]

array([139731.10583523, 140963.86680229, 139731.10583523, 140963.86680229,
       139731.10583523, 136603.98874304, 138498.34486817, 140963.86680229,
       140963.86680229, 134709.63261791])

In [33]:
svr.predict(X_test)[:10]

array([132320.02899649, 132320.02901338, 132320.02899649, 132320.02901338,
       132320.02899649, 132319.99997809, 132320.02897956, 132320.02901338,
       132320.02901338, 132319.97098703])

In [34]:
rfr.predict(X_test)[:10]

array([137645.89717234, 144856.08243552, 137645.89717234, 144856.08243552,
       137645.89717234, 139060.9651468 , 127301.57851842, 144856.08243552,
       144856.08243552, 133126.00695413])

In [35]:
etr.predict(X_test)[:10]

array([137223.63636364, 143850.45263158, 137223.63636364, 143850.45263158,
       137223.63636364, 138428.42857143, 126973.52941176, 143850.45263158,
       143850.45263158, 133661.73076923])

In [50]:
gbr.predict(X_test)

array([137205.37690166, 143858.38950502, 137205.37690166, 143858.38950502,
       137205.37690166, 138654.90498737, 126988.02053511, 143858.38950502,
       143858.38950502, 133672.58853887, 199757.44866974, 133672.58853887,
       137205.37690166, 137205.37690166, 143858.38950502, 138654.90498737,
       133672.58853887, 143858.38950502, 143858.38950502, 133672.58853887,
       143858.38950502, 138654.90498737, 143858.38950502, 120113.32302085,
       143858.38950502, 133672.58853887, 133672.58853887, 143858.38950502,
       143858.38950502, 137205.37690166, 137205.37690166, 199757.44866974,
       143858.38950502, 137205.37690166, 143858.38950502, 143858.38950502,
       133672.58853887, 143858.38950502, 143858.38950502, 143858.38950502,
       138654.90498737, 120113.32302085, 199757.44866974, 133672.58853887,
       126988.02053511, 133672.58853887, 143858.38950502, 143858.38950502,
       120113.32302085, 143858.38950502, 137205.37690166, 133672.58853887,
       126988.02053511, 1

In [48]:
xgbr.predict(X_test)

array([137223.62, 143850.44, 137223.62, 143850.44, 137223.62, 138428.4 ,
       126973.52, 143850.44, 143850.44, 133661.72, 199999.95, 133661.72,
       137223.62, 137223.62, 143850.44, 138428.4 , 133661.72, 143850.44,
       143850.44, 133661.72, 143850.44, 138428.4 , 143850.44, 120153.56,
       143850.44, 133661.72, 133661.72, 143850.44, 143850.44, 137223.62,
       137223.62, 199999.95, 143850.44, 137223.62, 143850.44, 143850.44,
       133661.72, 143850.44, 143850.44, 143850.44, 138428.4 , 120153.56,
       199999.95, 133661.72, 126973.52, 133661.72, 143850.44, 143850.44,
       120153.56, 143850.44, 137223.62, 133661.72, 126973.52, 138428.4 ,
       143850.44, 138428.4 ], dtype=float32)

In [38]:
ctr.predict(X_test)[:10]

array([137223.63636358, 143850.45263157, 137223.63636358, 143850.45263157,
       137223.63636358, 138428.43138012, 126973.52941474, 143850.45263157,
       143850.45263157, 133661.73025564])

In [39]:
lgbmr.predict(X_test)[:10]

array([134905.79259991, 143774.27381976, 134905.79259991, 143774.27381976,
       134905.79259991, 138841.77103811, 136638.46011467, 143774.27381976,
       143774.27381976, 132198.10487924])

### 7. Evaluación

In [40]:
y_test.head()

30       9272
126    161342
199     90000
142    126500
253     50000
Name: salary_in_usd, dtype: int64

In [41]:
from sklearn.metrics import mean_squared_error as mse  # error cuadratico medio

In [42]:
# regresion lineal

y_pred=linreg.predict(X_test)

mse(y_test, y_pred, squared=False)    # RMSE

70623.99159378039

In [43]:
# rfr

y_pred=rfr.predict(X_test)

mse(y_test, y_pred, squared=False)  # RMSE

75249.28640096482

In [ ]:
# svr

y_pred=svr.predict(X_test)

mse(y_test, y_pred, squared=False)  # RMSE

In [44]:
# boosting

y_pred=xgbr.predict(X_test)

mse(y_test, y_pred, squared=False)  # RMSE

75713.2425450172

In [45]:
y_pred=ctr.predict(X_test)

mse(y_test, y_pred, squared=False)  # RMSE

75713.14777221609

In [46]:
y_pred=ctr.predict(X_train)  # error en el entrenamiento

mse(y_train, y_pred, squared=False)  # RMSE

74573.54832909645